network:
  version: 2
  wifis:
    HotSpot:
      renderer: NetworkManager
      match: {}
      ipv6-address-generation: "stable-privacy"
      access-points:
        "SSID":
          auth:
            key-management: "psk"
            password: "astrophotography"
          mode: "ap"
          band: "2.4GHz" # 5GHz alternative
          channel: 6
          networkmanager:
            name: "HotSpot"
            passthrough:
              ipv6.method: "disabled"
              ipv6.ip6-privacy: "-1"
              proxy._: ""
      networkmanager:
        name: "HotSpot"
